package junit.base;

import org.junit.Test;

public class JunitException {
@Test
public void test1() {
System.out.println("Test 1");
}
@Test
public void test2() {
System.out.println("Test 2");
}
@Test
public void test3() {
System.out.println("Test 3");
int a=20/0;
}
@Test
public void test4() {
System.out.println("Test 4");
}
	

}
